from pathlib import Path
import json,struct
root=Path(__file__).parent
variants={'retro-light':'Retro Light','retro-dark':'Retro Dark','pokedex-light':'Pokédex Light','pokedex-dark':'Pokédex Dark'}
order=['today','focus','issues','projects','insights','collection','usage','settings','menu','floating','timer','planning','time-block','new-issue','issue-focus','task','partner','pet','session','check-in','time-up','reset','forfeit','storage']
def sort_key(name):
 family=next((x for x in order if name.startswith(x)), 'zzz')
 return (order.index(family) if family in order else 999, name)
names=sorted((p.stem for p in (root/'sources').glob('*.png')),key=sort_key)
labels={'today':'Today','focus-running':'Focus · Running','focus-paused':'Focus · Paused','focus-idle':'Focus · Idle','insights-1':'Insights · Day','insights-7':'Insights · Week','insights-30':'Insights · Month','projects-list':'Projects · List','projects-grid':'Projects · Grid','collection-dex':'Collection · Pokédex','collection-log':'Collection · Catch log','collection-detail':'Collection · Pokémon details','new-issue':'New issue window','task-setup':'Task timer setup','timer-alert':'Timer alert window','menu-detached':'Detached menu window','pet-speech':'Pet · Speech bubble','planning-calendar':'Planning date popup','time-block-editor':'Edit time block','planning-add-issue':'Add an issue to Today','timer-editor':'Adjust timer','issue-focus-duration':'Choose issue focus duration','project-issue-filter':'Project issue status filter','partner-details-popup':'Partner details popup','storage-needs-egg':'Storage · Egg needed','timer-detached':'Detached timer','timer-more-menu':'Timer actions menu','pet-hover':'Pet · Token and limit readout'}
screens=[]
for name in names:
 with (root/'sources'/f'{name}.png').open('rb') as f:
  f.seek(16); w,h=struct.unpack('>II',f.read(8))
 screens.append({'id':name,'label':labels.get(name,name.replace('-',' · ').replace('inProgress','In progress').replace('completedToday','Completed today').title()),'width':w,'height':h,'source':f'sources/{name}.png','variants':{t:f'{t}/{name}.png' for t in variants}})
complete=sum((root/t/f'{n}.png').is_file() for t in variants for n in names)
manifest={'title':'PokeTasks v2 · Theme mockups','date':'2026-10-02','baseline':'Current v2 native screens with isolated sample data','implementation':'Visual exploration only; production source and installed app unchanged','completed':complete,'expected':len(names)*4,'variants':variants,'screens':screens,'font':{'retro':'Galmuri11 and Galmuri11 Bold','source':'https://github.com/quiple/galmuri','license':'SIL Open Font License 1.1'},'notes':['Current v2 layouts rendered from a disposable source snapshot with sample data.','Planning calendar is a static visual study of the existing popup with themed typography.','Original image concepts are preserved in concepts/.']}
(root/'manifest.json').write_text(json.dumps(manifest,indent=2))
html=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PokeTasks · Theme mockups</title><style>
*{box-sizing:border-box}body{margin:0;background:#f1f2f4;color:#202229;font:15px -apple-system,BlinkMacSystemFont,sans-serif}header{padding:22px 28px;background:white;border-bottom:1px solid #ddd;position:sticky;top:0;z-index:2}h1{font-size:23px;margin:0 0 6px}p{margin:0;color:#626774}nav{margin-top:16px;display:flex;flex-wrap:wrap;gap:10px;align-items:center}select,button{font:inherit;padding:8px 12px;border:1px solid #ccd0d6;border-radius:6px;background:white;color:inherit}nav>a{color:#365f9b;font-size:13px;text-decoration:none}select{min-width:260px;max-width:100%}#count{font-size:13px;margin-left:auto}main{padding:24px;max-width:1800px;margin:auto}#cards{display:grid;grid-template-columns:1fr 1fr;gap:24px}figure{margin:0;background:white;border:1px solid #d7dbe0;border-radius:10px;overflow:hidden}figcaption{padding:13px 16px;font-weight:600;display:flex;justify-content:space-between;align-items:center}figcaption a{font-size:12px;font-weight:400;color:#44618a}img{width:auto;max-width:100%;height:auto;display:block;margin:0 auto}figure>a{display:block;min-height:80px;background:#e4e7ec}#cards figure>a{padding:0}#baseline{margin:24px auto;max-width:1000px}#baseline[hidden]{display:none}.pending{padding:60px 20px;text-align:center;background:#fafafa;color:#7a808a}.pending[hidden]{display:none}footer{text-align:center;color:#767c86;font-size:12px;padding:20px}@media(max-width:850px){#cards{grid-template-columns:1fr}header{position:static}main{padding:12px}#count{margin-left:0}}
</style><header><h1>PokeTasks · Theme mockups</h1><p>Retro and Pokédex, in light and dark. Pixel fonts throughout Retro. Pages, windows, popups and Settings sections. Mockups only.</p><nav><button id="prev" aria-label="Previous screen">←</button><select id="screen" aria-label="Choose screen"></select><button id="next" aria-label="Next screen">→</button><label><input id="showSource" type="checkbox"> Show current screen</label><a href="PokeTasks-Theme-Mockups.zip" download>Save full mockup pack</a><span id="count"></span></nav></header><main><div id="cards"></div><figure id="baseline" hidden><figcaption>Current reference</figcaption><img id="source" alt="Current PokeTasks screen"></figure></main><footer>Sample data · 2 October 2026 · Click an image to inspect it at full size · Retro font: <a href="https://github.com/quiple/galmuri">Galmuri</a></footer><script>
let data=__DATA__,selected=location.hash.slice(1)||'today';const picker=document.getElementById('screen'),cards=document.getElementById('cards');for(const s of data.screens){const o=document.createElement('option');o.value=s.id;o.textContent=s.label;picker.append(o)}function show(){const s=data.screens.find(s=>s.id===selected)||data.screens[0];selected=s.id;picker.value=s.id;history.replaceState(null,'','#'+s.id);cards.replaceChildren();for(const [id,label]of Object.entries(data.variants)){const f=document.createElement('figure'),cap=document.createElement('figcaption'),a=document.createElement('a'),img=document.createElement('img'),pending=document.createElement('div');cap.textContent=label;a.href=s.variants[id];a.target='_blank';a.rel='noopener';a.textContent='Full size ↗';cap.append(a);img.alt=label+' · '+s.label;pending.className='pending';pending.textContent='Mockup in progress';pending.hidden=true;const link=document.createElement('a');link.href=a.href;link.target='_blank';link.append(img);img.onerror=()=>{link.hidden=true;a.hidden=true;pending.hidden=false};img.src=s.variants[id];f.append(cap,link,pending);cards.append(f)}document.getElementById('source').src=s.source;document.getElementById('count').textContent=data.completed+' / '+data.expected+' mockups ready'}picker.onchange=()=>{selected=picker.value;show()};for(const [id,delta]of[['prev',-1],['next',1]])document.getElementById(id).onclick=()=>{const i=data.screens.findIndex(s=>s.id===selected);selected=data.screens[(i+delta+data.screens.length)%data.screens.length].id;show()};document.getElementById('showSource').onchange=e=>document.getElementById('baseline').hidden=!e.target.checked;show();setInterval(async()=>{try{const fresh=await fetch('manifest.json?'+Date.now()).then(r=>r.json());if(fresh.completed!==data.completed){data=fresh;show()}}catch{}},15000);
</script></html>'''
(root/'index.html').write_text(html.replace('__DATA__',json.dumps(manifest)))
print(f'{complete}/{len(names)*4} assets, {len(names)} screens')
